### ISSUE TITLE
com.mongodb.MongoSocketReadException: Prematurely reached end of stream

### ISSUE THREAD

**Issue by Myeongjoon** [Myeongjoon/tourAPI#5]
서버에 보면 mongoDB가 돌아가는 것을 볼 수 있는데, 아래와 같은 에러가 뜸.

뭔지는 모르겠지만, 아마 wifi일 수도 있으니 집에서 확인.

```
Mar 29, 2017 9:54:10 AM com.mongodb.diagnostics.logging.JULLogger log
정보: No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=104.199.130.130:80, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
Mar 29, 2017 9:54:11 AM com.mongodb.diagnostics.logging.JULLogger log
정보: Exception in monitor thread while connecting to server 104.199.130.130:80
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.connection.SocketStream.read(SocketStream.java:88)
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:491)
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:221)
	at com.mongodb.connection.CommandHelper.receiveReply(CommandHelper.java:134)
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:121)
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:83)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:43)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:128)
	at java.lang.Thread.run(Thread.java:745)

Mar 29, 2017 9:54:14 AM com.mongodb.diagnostics.logging.JULLogger log
정보: Opened connection [connectionId{localValue:5, serverValue:718}] to 104.199.130.130:80
Mar 29, 2017 9:54:14 AM com.mongodb.diagnostics.logging.JULLogger log
정보: Monitor thread successfully connected to server with description ServerDescription{address=104.199.130.130:80, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[2, 0, 4]}, minWireVersion=0, maxWireVersion=0, maxDocumentSize=16777216, roundTripTimeNanos=109317313}
null
Mar 29, 2017 9:54:14 AM com.mongodb.diagnostics.logging.JULLogger log
정보: Closed connection [connectionId{localValue:6}] to 104.199.130.130:80 because there was a socket exception raised by this connection.
findwithDB Exception
com.mongodb.MongoSocketReadException: Prematurely reached end of stream
```

**Comment by Myeongjoon** [comment]
- 현재 집에서 되는걸 보니, 와이파이 문제인듯 하다.
